### ISSUE TITLE
BBCodes added by this extension are not parsed

### ISSUE THREAD

**Issue by Zoddo** [cYbercOsmOnauT/wysiwygsceditorphpbb#12]
The BBCodes added by this extension are not parsed as in this screenshot:

![capture](https://cloud.githubusercontent.com/assets/5215545/8724080/f7198064-2bcf-11e5-815b-75b714444a16.PNG)

**Comment by cYbercOsmOnauT** [comment]
This means that the migrations were not inserted into the database. Try to disable, Delete data (not really needed, just to be sure) and reenable the Extension. I don't know how simple INSERT queries did not work on your database.

**Comment by cYbercOsmOnauT** [comment]
Or did you maybe install another extension later that deleted this bbcodes from the database? I don't know.

**Comment by Zoddo** [comment]
I tested from a phpBB 3.1.5 freshly installed via quickinstall.

The BBCodes appears in the ACP but doesn't work even after a clean of the cache.

**Comment by Zoddo** [comment]
When I delete and recreate a BBCode, it's correctly parsed.

**Comment by cYbercOsmOnauT** [comment]
What is quickinstall? Please install it the way it should be by enabling it on the ACP - Customize. I guess your quickinstall does not do the Migrations part.

**Comment by Zoddo** [comment]
https://www.phpbb.com/customise/db/official_tool/phpbb3_quickinstall/

**Comment by cYbercOsmOnauT** [comment]
Ah okay.. so that means that this Quickinstall activates the extensions but is not going through their migrations. Also Quickinstall is for phpBB 3.1.3. My extension is optimized for phpBB 3.1.5 and greater. Should still be no problem. I think the problem is on the Quickinstall side and you should talk to the creator of this thing. When you activate the WYSIWYG editor manually on one board you will see that everything works fine. So please ask the right person ;) I am not here to fix the fault of his script.

**Comment by Zoddo** [comment]
QuickInstall isn't an extension, but a tool (developed by phpBB team) that installs phpBB in one click. I install/activate the extension with the normal ways on the ACP > Customize.

A user on the French community has experimented the same issue (he haven't installed his board with quickinstall) : http://forums.phpbb-fr.com/extensions-support-independantes-phpbb31/sujet205486.html

**Comment by cYbercOsmOnauT** [comment]
I don't speak french.. sorry ;)

**Comment by Zoddo** [comment]
Yes, that's why I reported the issue here :)

**Comment by cYbercOsmOnauT** [comment]
I tried it out on my testboard (3.1.5). Disabled the extension. Deleted its data.. all **new** BBCodes were gone. Then I enabled it again.. looked inside **POSTING* - **BBCodes* and what did I see? All the BBCodes that were added by my extension.

I cannot see any faulty behaviour here.

**Comment by Zoddo** [comment]
The BBCodes appears in the ACP but doesn't work even after a clean of the cache.
When I delete and recreate a BBCode, it's correctly parsed.

I think you should to test with a freshly installed board without other extensions :)

**Comment by cYbercOsmOnauT** [comment]
But how can they not work when you see them in the ACP? This extension only changes the way of parsing for color and size. All other BBCodes are parsed *the normal way*. So if you see them inside the BBCodes tab it means that they also get parsed.

**Comment by Zoddo** [comment]
Ok, I've find what is the bug. It's because the migrations start the insertion of BBCode from id "1" (if there is no other bbcodes: always dev/test his extension from a clean board).

You need to check that ids of your custom bbcodes is greater than the core bbcode ids.
See the ACP module: https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/acp/acp_bbcodes.php#L252

**Comment by cYbercOsmOnauT** [comment]
No I don't start with 1

https://github.com/cYbercOsmOnauT/wysiwygsceditorphpbb/blob/master/cosmo/sceditor/migrations/bbcodedata.php

Look at the lines 44 and below

**Comment by Zoddo** [comment]
If there isn't other custom bbcodes, It's start with "1".

![image](https://cloud.githubusercontent.com/assets/5215545/8727564/af1f8356-2be0-11e5-9ab5-3b9674cf8ff3.png)

**Comment by cYbercOsmOnauT** [comment]
Ah... now I understand what you meant. Okay, that can be fixed fast... wait a minute ;)
