### ISSUE TITLE
HTML table with visible borders in editor

### ISSUE THREAD

**Issue by stephanedaviet** [cYbercOsmOnauT/wysiwygsceditorphpbb#13]
Is it possible to get visible borders in the editor when creating an HTML table? In the current state, it's quite difficult to create a table because cells are barely visible.

**Comment by cYbercOsmOnauT** [comment]
This is a _CSS Problem_.
Editing [jquery.sceditor.default.min.css](https://github.com/cYbercOsmOnauT/wysiwygsceditorphpbb/blob/master/cosmo/sceditor/styles/all/template/js/jquery.sceditor.default.min.css) should help you ;)

**Comment by stephanedaviet** [comment]
Perfect, thanks.

**Comment by stephanedaviet** [comment]
I think it's definitely a bug, a CSS one, but a bug :-). I have fixed it by editing the _editarea.css_ in https://github.com/cYbercOsmOnauT/wysiwygsceditorphpbb/pull/15.
