### ISSUE TITLE
Error when including sceditor's CSS

### ISSUE THREAD

**Issue by Titou74** [cYbercOsmOnauT/wysiwygsceditorphpbb#20]
On file "styles\all\template\event\overall_header_head_append.html", there are on line 2 "" , but the "default.min.css" file don't exists : the correct file name is "jquery.sceditor.default.min.css".

**Comment by Titou74** [comment]
My bad, I forget the "theme" folder when I navigate on the folders ...

**Comment by cYbercOsmOnauT** [comment]
So it's solved?

Am 11.09.2016 um 23:50 schrieb Titou74:

**Comment by Titou74** [comment]
Yes, this issue is solved ;-)
