### ISSUE TITLE
nested lists fully broken

### ISSUE THREAD

**Issue by naturalgeek** [cYbercOsmOnauT/wysiwygsceditorphpbb#21]
**Tested on 3.1.10 and 3.2.0**

when you create a nested list, the output BB Code is wrong!

**Output is:**

[ul]
[li]eins[/li]
[ul]
[li]zwei[/li]
[ul]
[li]drei[/li]
[/ul]
[/ul]
[/ul]

**Instead of:**

[ul]
[li]eins
[ul]
[li]zwei
[ul]
[li]drei[/li]
[/ul]
[/li]
[/ul]
[/li]
[/ul]

This example is made in phpbb 3.2, the problem also exists on phpbb 3.1 but
with [list] instead of [li]
when i paste richtext, there will be also some [/ul] tags replaced with [/ol]. no idea why.

I will try to fix it but if someone is more familiar with the codebase it might be more easy to fix for you

Thx!

**Comment by davidshq** [comment]
I've experienced the same issue as well.

**Comment by naturalgeek** [comment]
seems to be not related to this project but:

https://github.com/samclarke/SCEditor

**Comment by cYbercOsmOnauT** [comment]
I will update SCEditor. Lets see if that will solve the problem.

**Comment by cYbercOsmOnauT** [comment]
```
[ul]
[li]eins
[ul]
[li]zwei
[ul]
[li]drei[/li]
[/ul]
[/li]
[/ul]
[/li]
[/ul]
```

Used this with SCEditor 1.5.2. Clicked on Preview.. and back.. posted... edit... still the same

**Comment by naturalgeek** [comment]
i've created a bug report for SCEditor too

https://github.com/samclarke/SCEditor/issues/553

**Comment by cYbercOsmOnauT** [comment]
It's definitely a problem with SCEditor. This is the HTML that gets created inside the WYSIWYG Editor.

```<ul>
  <li>One</li>
  <ul>
    <li>Two</li>
    <ul>
      <li>Three</li>
    </ul>
    <li>Two</li>
  </ul>
  <li>One</li>
</ul>```

**Comment by naturalgeek** [comment]
Fixed in SCEditor:
https://github.com/samclarke/SCEditor/issues/553

**Comment by cYbercOsmOnauT** [comment]
Thanks. I am just not sure if I should put a quickfix into my code or better wait for the release of v2 from SCEditor.

**Comment by naturalgeek** [comment]
quickfix! :)
