### ISSUE TITLE
SQL-Error on 3.2

### ISSUE THREAD

**Issue by b-vetter** [cYbercOsmOnauT/wysiwygsceditorphpbb#22]
I get the following error on phpBB 3.2:

> Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'amzecho_phpbb_test2.phpwg_smilies.code' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [1055]

**Comment by AutoJunkie79** [comment]
I'm also on 3.2 and got something similar, but for MSSQL:

![sqlerror](https://cloud.githubusercontent.com/assets/25411186/23073463/a4a535f4-f503-11e6-975c-3ea8b14b3f51.PNG)

**Comment by cYbercOsmOnauT** [comment]
MSSQL is nothing I use. Let me take a look at it.

**Comment by b-vetter** [comment]
I using MySQL and PHP 7.1. ;)

**Comment by cYbercOsmOnauT** [comment]
Which MySQL version?

**Comment by b-vetter** [comment]
5.7.17

**Comment by cYbercOsmOnauT** [comment]
Can you try out the following? Open `cosmo/sceditor/event/sce.php` and change in line 69 the following `GROUP BY smiley_url` to `GROUP BY smiley_url,code`

**Comment by b-vetter** [comment]
Yes, that works perfect!
Thank you!

**Comment by AutoJunkie79** [comment]
This worked for me as well on MSSQL! Thank you!

**Comment by cYbercOsmOnauT** [comment]
#58ed3cfb329389ce8165f95d65cd6572571c54c8 fixed this problem
