### ISSUE TITLE
Problem with SVG-Emojis

### ISSUE THREAD

**Issue by b-vetter** [cYbercOsmOnauT/wysiwygsceditorphpbb#23]
I use the following Emoji One Pack:
https://github.com/sylvaindurand/emojione-phpbb

If I add an Emoji in the editor, the editor shows it in full size.:
![wysiwygsceditorphpbb_emoji](https://cloud.githubusercontent.com/assets/24404910/23093055/1ced4e9a-f5d9-11e6-99a4-587a9d014a8a.PNG)

**Comment by Nitair** [comment]
Did you follow these instructions?

## Extend to Emoji
Since version 3.2, phpBB automatically converts emojis to images, but from a different provider.

To change it, edit `/vendor/s9e/text-formatter/src/Plugins/Emoji/Configurator.php` and change the line:

```php
return $template;
```

With:

```php
return '<img alt="{.}" class="smilies" src="./images/smilies/emojione/' . '{@seq}.' . 'svg" />';
```

**Comment by taitai42** [comment]
how did you get the smiley to display with this editor, they disappeared since i installed the extension
