### ISSUE TITLE
YouTube videos not showing in post

### ISSUE THREAD

**Issue by AutoJunkie79** [cYbercOsmOnauT/wysiwygsceditorphpbb#24]
when attempting to embed a YouTube video, the clip shows up fine in the editor but not in the post. I'm not much of a developer, but it does appear that the video is being embedded in the final post even though it is not visible.

phpBB 3.2.0
PHP 7.1.1
ComBoot Theme (I switched back to prosilver and result is the same)

Enabled Extensions:

- Board Announcements 1.0.5 by phpBB
- Contact Admin 1.1.1 by rmcgirr83
- phpbb 3.1 WYSIWYG BBCode Editor 1.7.8 by (you)
- VigLink 1.0.0 by phpBB

Installed but not Enabled:

- Advanced BBCode Box 3.1.3 by vse
- File Download 1.0.2 by dmzx

**_[ Working in the editor ]_**

![editor](https://cloud.githubusercontent.com/assets/25411186/23174975/07fd4bca-f82c-11e6-8d77-b2e2132ffb82.PNG)

**_[ Actual post ]_**

![post](https://cloud.githubusercontent.com/assets/25411186/23174983/0e77960e-f82c-11e6-9d3f-fb935e1ef059.png)

**_[ Inpsector Code Snippet ]_**

![inspect](https://cloud.githubusercontent.com/assets/25411186/23175006/1969b056-f82c-11e6-93c5-cb1e559a502a.PNG)

**Comment by AutoJunkie79** [comment]
Ok, so I did some more research, it appears this should have been fixed in SCEditor v1.5.0: [https://github.com/samclarke/SCEditor/issues/489](url)

However I see the same error in my inspector console:

![console](https://cloud.githubusercontent.com/assets/25411186/23176285/6a51a3f8-f830-11e6-8eed-db3b749a8aca.png)

and I appear to have SCEditor 1.5.2, I only recently installed your extension:

![sceditor_ver_verify](https://cloud.githubusercontent.com/assets/25411186/23176519/4af951f8-f831-11e6-9925-c621b2678bce.PNG)

Not sure to go from here, thank you for looking into this! Let me know how I can help.

**Comment by AutoJunkie79** [comment]
Also, the URL I actually put into the editor was https://youtu.be/25QyCxVkXwQ

**Comment by cYbercOsmOnauT** [comment]
The problem occurs because you have a secure domain and the YT videos gets loaded over unsecure http. I will look into this.

**Comment by AutoJunkie79** [comment]
The URL we see in the inspector/console is not the one I put into the editor. I copied and pasted the https://youtu.be/25QyCxVkXwQ URL straight from the YouTube page after clicking on "Share". It seems like the editor or something else might be parsing the URL I entered, taking the unique ID of the video (25QyCxVkXwQ) and re-inserting it as a variable into the non-secure version. This probably explains why the video does not show in the preview either.

**Comment by cYbercOsmOnauT** [comment]
Go to your ACP - POSTING - BBCodes, scroll down to **youtube** and click on ![Edit](https://www.phpbb.com/community/adm/images/icon_edit.gif) inside the _HTML Replacement_ change **http** to **https** and save it.

I will change this too in my project.

**Comment by AutoJunkie79** [comment]
Good find, I didn't even think to look there!

**Comment by cYbercOsmOnauT** [comment]
Don't close it until I commit the solution for the new users ;)

**Comment by AutoJunkie79** [comment]
Sorry very new to GitHub too. ^_^
