### ISSUE TITLE
Pulling Latest from GitHub Is Still 1.7.8?

### ISSUE THREAD

**Issue by davidshq** [cYbercOsmOnauT/wysiwygsceditorphpbb#26]
Hi Folks,

Not sure what I am doing wrong, but I cannot seem to get 1.7.8.1 (that fixes the sceditor nesting) to download. I click Clone or Download --> Download Zip. I delete the old cosmo directory and replace it with the cosmo directory in the downloaded zip.

When I go back to the forums and edit a nested post, it shows the nesting in the WYSIWYG, but then doesn't parse the code when I view it, for example see:

http://ccbusergroup.com/viewtopic.php?f=4&t=534&p=726#p726

I made a new post and it seems to do half and half - some it processes, some it doesn't:
http://ccbusergroup.com/viewtopic.php?f=15&t=551

Also, in the ACP Extensions Manager it still shows that I am using 1.7.8 not 1.7.8.1 even though I've replaced the file.

Any help is appreciated!

Thanks,
Dave

**Comment by Nitair** [comment]
Its working for me
![wysiwyg_version](https://user-images.githubusercontent.com/10914774/27217511-6a74c1b8-527a-11e7-9d1e-5bcc2e0eced2.png)

**Comment by cYbercOsmOnauT** [comment]
Ah great. Thanks! I have two kids and two jobs and a single father. So my free time is very small atm. :)

**Comment by Nitair** [comment]
Yeah no problem. Maybe I can help you out a bit since I'm using phpbb3.2 as my test enviroment. I'm usally a C++ programmer, but shouldn't be a big deal.

**Comment by cYbercOsmOnauT** [comment]
Yes sure.
