### ISSUE TITLE
Plugin problem after upgrade

### ISSUE THREAD

**Issue by mvldebian** [cYbercOsmOnauT/wysiwygsceditorphpbb#41]
Upgrade PHPBB from 3.2.8 to 3.3.0

Error:

Exception: The file "/var/www/clients/client1/web58/web/ext/cosmo/sceditor/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 10 (near "- @dbal.conn").

Error on disable plugin

Any idea?

**Comment by cYbercOsmOnauT** [comment]
I did not upgrade to 3.3.0 atm. Let me take a fast look.

**Comment by mvldebian** [comment]
I ended up getting help on the phpbb forum
the solution was to insert ' before and after in the lines below

 - '@dbal.conn'
 - '@template'
 - '@config'
 - '@user'
 - '%core.root_path%'

**Comment by cYbercOsmOnauT** [comment]
Oh nice. Good to know. :) I am still at work so I had no time.
